### ISSUE TITLE
Extract locales from JSON

### ISSUE THREAD

**Issue by DanielJaramillo94** [i18next/i18next-multiload-backend-adapter#6]
Hi, I'm trying to exctact locales from a API call wich response with a json that have a nested object with an array containing the languages I need.

Example

```
response = {
attr1: "some"
att2: "foo"
lang: {es: [...], en: [...]}
}
```

I need to extract _es_ and _en_ from this response.

Is there a way to achieve what I need using this plugin? Thank you!

**Comment by adrai** [comment]
Sorry, I don't fully understand what you want to achieve.
Can you please elaborate a bit more?

**Comment by DanielJaramillo94** [comment]
Off course,

Actually I have a React project using i18next to achieve changing languages between english and spanish. Currently my locales are stored in the project, so I just have the next init json

```
i18n.use(LanguageDetector).init({
  resources: {
    es: {
      translations: esLocale,
    },
    en: {
      translations: enLocale,
    },
  },
  fallbackLng: 'es',
  debug: false,

  ns: ['translations'],
  defaultNS: 'translations',

  keySeparator: false,

  interpolation: {
    escapeValue: false,
    formatSeparator: ',',
  },

  react: {
    wait: true,
  },
});
```

Now, the problem is we cannot have those locale files on the code, insted we have to store them in a server because they could change frequently. When I make the request to the backend I have the next response _res_ structure: 

```
res = {
   Benefits: { ... }
   ​Categories: { ... }
   Traducciones: {
	name: "Traducciones"
	en: { "benefit.brands": "More than 50 leading brands in the market", "benefit.constantvisits": "Constant and personalized visits to our clients", "benefit.delivertime": "Delivery in 48 hours", … }
	es: { "benefit.brands": "Más de 50 marcas líderes en el mercado", "benefit.constantvisits": "Visitas constantes y personalizadas a nuestros clientes", "benefit.delivertime": "Entrega en 48 Horas", … }
	   ​​}
}
```

were _en_ and _es_ objects (inside _Traducciones_) are objects I need to make translations.

My question is, how do I use these objects as resourses to init method? If it still not clear please make me know it.

**Comment by adrai** [comment]
I don't think this is solvable with this multiload adapter...
Can't you just split your language files and load them with i18next-http-backend, like in this example? https://github.com/i18next/react-i18next/tree/master/example/react

**Comment by DanielJaramillo94** [comment]
I don't really have access to the bakend

**Comment by adrai** [comment]
Then you need to create your own i18next backend, or use i18next-http-backend with a custom parse function.

Something like:

```js
import i18next from 'i18next';
import HttpApi from 'i18next-http-backend';

i18next.use(HttpApi).init({
  backend: {
    // loadPath: '/locales/{{lng}}/{{ns}}.json',
    loadPath: '/locales.json',
    parse: (data, language, namespace) => {
      return data.Traducciones[language];
    }
  },
});
```

?

**Comment by DanielJaramillo94** [comment]
Yes! That _language_ param of parse function was what I needed!
Thank you much for your fast response!!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
